services:
  frontend:
    build: ./frontend
    image: tesddev/frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    image: tesddev/backend:latest-01
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=production
      - CONNECTION_STRING=${CONNECTION_STRING}
      - JWT_SECRET=${JWT_SECRET}