name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker images
        run: |
          docker-compose --env-file ./.env build
          docker-compose push

      - name: Create .env file for deployment
        run: |
          echo "CONNECTION_STRING=${{ secrets.CONNECTION_STRING }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env